<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehiculesSeeder extends Seeder
{
    public function run(): void
    {
        $vehicules = [
            [
                'immatriculation' => 'AB-123-CD',
                'marque'          => 'Renault',
                'modele'          => 'Clio',
                'motorisation'    => 'Essence',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Manuelle',
                'prix_journalier' => 35.00,
                'image_url'       => 'https://example.com/images/renault-clio.jpg',
                'age_minimum'     => 21,
            ],
            [
                'immatriculation' => 'EF-456-GH',
                'marque'          => 'Peugeot',
                'modele'          => '208',
                'motorisation'    => 'Diesel',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Manuelle',
                'prix_journalier' => 38.00,
                'image_url'       => 'https://example.com/images/peugeot-208.jpg',
                'age_minimum'     => 21,
            ],
            [
                'immatriculation' => 'IJ-789-KL',
                'marque'          => 'Citroën',
                'modele'          => 'C3',
                'motorisation'    => 'Essence',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 40.00,
                'image_url'       => 'https://example.com/images/citroen-c3.jpg',
                'age_minimum'     => 21,
            ],
            [
                'immatriculation' => 'MN-012-OP',
                'marque'          => 'Volkswagen',
                'modele'          => 'Golf',
                'motorisation'    => 'Diesel',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Manuelle',
                'prix_journalier' => 55.00,
                'image_url'       => 'https://example.com/images/vw-golf.jpg',
                'age_minimum'     => 21,
            ],
            [
                'immatriculation' => 'QR-345-ST',
                'marque'          => 'BMW',
                'modele'          => 'Série 3',
                'motorisation'    => 'Essence',
                'nb_portes'       => 4,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 95.00,
                'image_url'       => 'https://example.com/images/bmw-serie3.jpg',
                'age_minimum'     => 25,
            ],
            [
                'immatriculation' => 'UV-678-WX',
                'marque'          => 'Mercedes',
                'modele'          => 'Classe A',
                'motorisation'    => 'Diesel',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 110.00,
                'image_url'       => 'https://example.com/images/mercedes-classea.jpg',
                'age_minimum'     => 25,
            ],
            [
                'immatriculation' => 'YZ-901-AB',
                'marque'          => 'Audi',
                'modele'          => 'A3',
                'motorisation'    => 'Essence',
                'nb_portes'       => 4,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 100.00,
                'image_url'       => 'https://example.com/images/audi-a3.jpg',
                'age_minimum'     => 25,
            ],
            [
                'immatriculation' => 'CD-234-EF',
                'marque'          => 'Toyota',
                'modele'          => 'Yaris',
                'motorisation'    => 'Hybride',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 45.00,
                'image_url'       => 'https://example.com/images/toyota-yaris.jpg',
                'age_minimum'     => 21,
            ],
            [
                'immatriculation' => 'GH-567-IJ',
                'marque'          => 'Toyota',
                'modele'          => 'RAV4',
                'motorisation'    => 'Hybride',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 85.00,
                'image_url'       => 'https://example.com/images/toyota-rav4.jpg',
                'age_minimum'     => 23,
            ],
            [
                'immatriculation' => 'KL-890-MN',
                'marque'          => 'Ford',
                'modele'          => 'Focus',
                'motorisation'    => 'Essence',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Manuelle',
                'prix_journalier' => 48.00,
                'image_url'       => 'https://example.com/images/ford-focus.jpg',
                'age_minimum'     => 21,
            ],
            [
                'immatriculation' => 'OP-123-QR',
                'marque'          => 'Ford',
                'modele'          => 'Mustang',
                'motorisation'    => 'Essence',
                'nb_portes'       => 2,
                'nb_places'       => 4,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 150.00,
                'image_url'       => 'https://example.com/images/ford-mustang.jpg',
                'age_minimum'     => 25,
            ],
            [
                'immatriculation' => 'ST-456-UV',
                'marque'          => 'Tesla',
                'modele'          => 'Model 3',
                'motorisation'    => 'Électrique',
                'nb_portes'       => 4,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 130.00,
                'image_url'       => 'https://example.com/images/tesla-model3.jpg',
                'age_minimum'     => 23,
            ],
            [
                'immatriculation' => 'WX-789-YZ',
                'marque'          => 'Tesla',
                'modele'          => 'Model Y',
                'motorisation'    => 'Électrique',
                'nb_portes'       => 5,
                'nb_places'       => 7,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 145.00,
                'image_url'       => 'https://example.com/images/tesla-modely.jpg',
                'age_minimum'     => 23,
            ],
            [
                'immatriculation' => 'AB-012-CD',
                'marque'          => 'Dacia',
                'modele'          => 'Sandero',
                'motorisation'    => 'Essence',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Manuelle',
                'prix_journalier' => 28.00,
                'image_url'       => 'https://example.com/images/dacia-sandero.jpg',
                'age_minimum'     => 21,
            ],
            [
                'immatriculation' => 'EF-345-GH',
                'marque'          => 'Dacia',
                'modele'          => 'Duster',
                'motorisation'    => 'Diesel',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Manuelle',
                'prix_journalier' => 52.00,
                'image_url'       => 'https://example.com/images/dacia-duster.jpg',
                'age_minimum'     => 21,
            ],
            [
                'immatriculation' => 'IJ-678-KL',
                'marque'          => 'Nissan',
                'modele'          => 'Qashqai',
                'motorisation'    => 'Essence',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 72.00,
                'image_url'       => 'https://example.com/images/nissan-qashqai.jpg',
                'age_minimum'     => 23,
            ],
            [
                'immatriculation' => 'MN-901-OP',
                'marque'          => 'Fiat',
                'modele'          => '500',
                'motorisation'    => 'Essence',
                'nb_portes'       => 3,
                'nb_places'       => 4,
                'type_boite_vitesse' => 'Manuelle',
                'prix_journalier' => 32.00,
                'image_url'       => 'https://example.com/images/fiat-500.jpg',
                'age_minimum'     => 21,
            ],
            [
                'immatriculation' => 'QR-234-ST',
                'marque'          => 'Hyundai',
                'modele'          => 'Tucson',
                'motorisation'    => 'Hybride',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 78.00,
                'image_url'       => 'https://example.com/images/hyundai-tucson.jpg',
                'age_minimum'     => 23,
            ],
            [
                'immatriculation' => 'UV-567-WX',
                'marque'          => 'Kia',
                'modele'          => 'Sportage',
                'motorisation'    => 'Hybride',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 75.00,
                'image_url'       => 'https://example.com/images/kia-sportage.jpg',
                'age_minimum'     => 23,
            ],
            [
                'immatriculation' => 'YZ-890-AB',
                'marque'          => 'Porsche',
                'modele'          => 'Cayenne',
                'motorisation'    => 'Essence',
                'nb_portes'       => 5,
                'nb_places'       => 5,
                'type_boite_vitesse' => 'Automatique',
                'prix_journalier' => 250.00,
                'image_url'       => 'https://example.com/images/porsche-cayenne.jpg',
                'age_minimum'     => 25,
            ],
        ];

        DB::table('vehicules')->insert($vehicules);
    }
}